domain: suisen-cp.github.io
baseurl: /
url: https://suisen-cp.github.io

theme: minima
plugins:
  - jekyll-feed

atcoder-virtual-contest-generator:
  title: AOJ-ICPC problem set generator
  description: Generates problem sets on AOJ-ICPC
  url: atcoder-virtual-contest-generator